version: '3.8'

services:
  frontend:
    build:
      context: ../..
      dockerfile: docker/development/Dockerfile
    ports:
      - "${VITE_PORT}:${VITE_PORT}"
    volumes:
      - ../../:/srv/app
      - /srv/app/node_modules
    env_file:
      - ../../.env.development.local
    command: npm run dev:web