services:
  frontend:
    build:
      context: ../..
      dockerfile: docker/development/Dockerfile
    ports:
      - "8069:8069"
    volumes:
      - ../../:/srv/app
      - /srv/app/node_modules
    env_file:
      - ../../.env.development.local
    command: npm run dev:web