services:
  frontend:
    container_name: famsy-frontend
    build:
      context: ../..
      dockerfile: docker/development/Dockerfile
    ports:
      - "8069:8069"
      - "24678:24678"
    volumes:
      - ../../:/srv/app
      - /srv/app/node_modules
    env_file:
      - ../../.env.development.local
    environment:
      - NODE_ENV=development
    command: ["pnpm", "run", "dev:server"]