version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: famsy
      POSTGRES_USER: famsyUser
      POSTGRES_PASSWORD: famsyPass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: