spring:
  application:
    name: backend-java
  datasource:
    url: jdbc:postgresql://localhost:5432/famsy
    username: famsyUser
    password: famsyPass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG