spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/famsy
    username: famsyUser
    password: famsyPass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true

  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080
  servlet:
    context-path: /api/v1
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

famsy:
  security:
    jwt:
      access-token:
        expiration: 5m
      refresh-token:
        expiration: 10d
      session:
        expiration: 30d
      issuer: famsy
      secret: ${JWT_SECRET:5e9366349290a82f53e81b2c359f9554a3c291b284e482ab3c3aab98d3e044b9}
      cookie:
        secure: true
        http-only: true
        same-site: Lax
        domain: localhost