services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: famsyUser
      MINIO_ROOT_PASSWORD: famsyPass
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - backend_net

networks:
  backend_net:
    external: true

volumes:
  minio_data: