services:
  postgres:
    container_name: postgres
    image: postgres
    command: -p ${POSTGRES_PORT}
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data

  api:
    container_name: api
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules/
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    #  DATABASE_URL: ${DATABASE_URL}
    ports:
      - ${APP_PORT}:${APP_PORT}
    links:
      - redis
    depends_on:
      - postgres
      - redis

  redis:
    container_name: redis
    image: redis
    command: --port ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    expose:
      - ${REDIS_PORT}
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
  postgres:
