services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: famsy
      POSTGRES_USER: famsyUser
      POSTGRES_PASSWORD: famsyPass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_net

networks:
  backend_net:
    name: backend_net
    external: true

volumes:
  postgres_data: